FIX

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,8 +1,8 @@
- name: Verificar Estabilidad del Sitio Web
+name: Verificar Estabilidad del Sitio Web
 
 on:
   schedule:
-    - cron: '0 0 * * *'  # Ejecuta el trabajo a medianoche UTC
+    - cron: '0 10 * * *'  # Ejecuta el trabajo a las 10 AM UTC
 
 jobs:
   check-site:
@@ -24,10 +24,11 @@ jobs:
         run: python security.py
       - name: Configurar Git
         run: |
-          git config --global user.name 'GitHub Actions'
-          git config --global user.email 'actions@github.com'
+          git config --global user.name 'edujbarrios'
+          git config --global user.email 'eduardojbarriosgarcia@gmail.com'
       - name: Hacer commit de los cambios
         run: |
           git add checks/log.csv
-          git commit -m "Checks done and page running" || echo "No changes to commit"
-          git push
+          git commit -m "Security checks completed and page running"
+          git push || echo "No changes to commit or push failed"
+
